name: fantastic_image_gallery
description: "fantastic gallery images using ai"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  envied: ^1.0.0
  dart_openai: ^5.1.0
  get: ^4.6.6
  hugeicons: ^0.0.7
  intl: ^0.19.0
  fluttertoast: ^8.2.8
  path_provider: ^2.1.5
  external_path: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.11
  envied_generator: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - asset/image/christmas/
    - asset/image/comic/
    - asset/image/cyberpunk/
    - asset/image/disney/
    - asset/image/fantasy/
    - asset/image/halloween/
    - asset/image/landscape/
    - asset/image/logo/
    - asset/image/neon/
    - asset/image/sketch/
    - asset/image/studio_ghibli/
    - asset/image/style_menu/

